spring:
  profiles:
    active: dev
  application:
    name: java-rest-service-architecture
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 10Mb
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 1000
    min-idle: 5
    initial-size: 5
  Mybatis:
    mapper-locations: classpath*:mapper/*Mapper.xml
    confirguration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      jdbc-type-for-null: "NULL"

  authorizatioin:
    jwt:
      expireMinutes: 50
      key: xxx

  server:
    context-path: /api