#!/bin/bash

for file in $(git diff --cached --name-only | grep -E '\.(java)$')
do
  git show ":$file" | mvn clean checkstyle:checkstyle "$file" # we only want to lint the staged changes, not any un-staged changes
  if [ $? -ne 0 ]; then
    echo "xxxx"
    exit 1 # exit with failure status
  fi
done